version: "2"

services:
    database:
        container_name: mysql_database
        image: mysql:5.6
        env_file:
            - ./docker/env/mysql.development.env
        ports:
            - "3306:3306"
        networks:
            - meetcentrale-network
    node-tester:
        container_name: node-tester1
        build:
            context: .
            dockerfile: docker/node.dockerfile
        ports:
            - "80:3000"
        env_file:
            - ./docker/env/nodejs.development.env
        networks:
            - meetcentrale-network
        depends_on:
            - database

networks:
    meetcentrale-network:
        driver: bridge
